{{- range $name, $service := .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
    spec:
      serviceAccountName: {{ $name }}
      containers:
        - name: {{ $name }}
          image: {{ $.Values.image.repository }}:{{ $name }}-{{ $.Values.image.tag }}
          ports:
            - containerPort: {{ $service.containerPort }}
          {{- with $service.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
  ports:
    - port: 80
      targetPort: {{ $service.containerPort }}
  type: ClusterIP
{{- end }}
